spring:

  application:
    name: Courrier-App
  datasource:
    url: jdbc:mysql://customerdatabase.czg44uy4kppz.eu-north-1.rds.amazonaws.com/courrier

    username: admin
    password: Xperiaz123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8088




aws:
  access-key: AKIA6ODU22DK7W3X4R6W
  secret-key : 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
  region : eu-north-1
  s3:
  bucket-name : bucketscustomerdeliveryapp