spring:


  application:
    name: Orders-App
  datasource:
    url: jdbc:mysql://customerdatabase.czg44uy4kppz.eu-north-1.rds.amazonaws.com/orders

    username: admin
    password: Xperiaz123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8086

